Feat/event creating
draskonovakovic/back-end pull request #2
Opened 2024-12-02 08:29 UTC by draskonovakovic

The PR I am opening contains the following:

    Login/Logout: User authentication has been implemented using JWT. Upon user login, a token containing user information is created and sent to the frontend. An authMiddleware has been added to verify whether a token is included in the Authorization header, ensuring that certain functionalities cannot be accessed by unauthenticated users.

    Events: CRUD operations for managing events.

    WebSocket: Enables sending a message about newly created events to allow real-time display of the same.
    
    @ivan-at-2c @milan-at-2c

2024-12-02 12:06 UTC, igor-at-2c requested changes

2024-12-02 12:06 UTC, igor-at-2c commented on src/app.ts
> +/// <reference path="./utilis/types.d.ts" />
Zbog cega ovo koristis?

2024-12-02 12:06 UTC, igor-at-2c commented on src/controllers/authController.ts
> +      return res.status(401).json({ error: error.message });
Ovde handlujes samo slucajeve gde je korisnik uspesno ulogvan ili nije uspeo da se uloguje. 
- Korisnik sa unetim username-om ne postoji
- Doslo je do greske prilikom rada sa bazom
- Greska u kodu, neka tvoja funkcija nije vratila dobru vrednost

Potrebno je vratiti odgovrajuce statuse i error poruke u zavisnosti od slucaja

2024-12-02 12:06 UTC, igor-at-2c commented on src/controllers/eventController.ts
> +            res.status(500).json({ success: false, message: error.message });
Isto kao u login kontroleru, ne treba da bude vracen error 500 sta god da se desi.

2024-12-02 12:06 UTC, igor-at-2c commented on src/controllers/eventController.ts
> +            const creatorId = req.user?.id;
Sta ako user ne postoji u req objektu?

2024-12-02 12:06 UTC, igor-at-2c commented on src/controllers/eventController.ts
> +        const event = await eventService.getEventById(Number(req.params.id));
Gde ti je validacija request body-ja?

2024-12-02 12:06 UTC, igor-at-2c commented on src/controllers/eventController.ts
> +        const event = await eventService.updateEvent(Number(req.params.id), req.body);
Gde ti je validacija request body-ja?

2024-12-02 12:06 UTC, igor-at-2c commented on src/controllers/eventController.ts
> +        await eventService.deleteEvent(Number(req.params.id));
Gde ti je validacija request body-ja?

2024-12-02 12:06 UTC, igor-at-2c commented on src/controllers/authController.ts
> +    return res.status(200).json({});
Cemu sluzi ova provera?

2024-12-02 12:06 UTC, igor-at-2c commented on src/routes/eventRoutes.ts
> +router.get('/:id', eventController.getEventById);
Mozes korisiti .path() i onda ces moci da appendujes vise metoda od jednom

2024-12-02 12:06 UTC, igor-at-2c commented on src/services/eventService.ts
> +      const deleted = await eventRepository.delete(id);
Mogao bi da vratis ID eventa ili ceo event nakon sto ga obrises

2024-12-02 12:06 UTC, igor-at-2c commented on src/services/eventService.ts
> +      const event = await eventRepository.findById(id);
Fali ti try catch, sta ces da vratis ako pukne nesto u eventRepository?

2024-12-02 12:06 UTC, igor-at-2c commented on src/services/eventService.ts
> +      return eventRepository.findAll();
Fali ti try catch, sta ces da vratis ako pukne nesto u eventRepository?

2024-12-02 12:06 UTC, igor-at-2c commented on src/services/eventService.ts
> +      const updatedEvent = await eventRepository.update(id, event);
Fali ti try catch, sta ces da vratis ako pukne nesto u eventRepository?

2024-12-02 12:06 UTC, igor-at-2c commented on src/services/eventService.ts
> +      const deleted = await eventRepository.delete(id);
Fali ti try catch, sta ces da vratis ako pukne nesto u eventRepository?

2024-12-02 15:03 UTC, draskonovakovic commented on src/app.ts
> +/// <reference path="./utilis/types.d.ts" />
Ovo mi je bilo jedino resenje koje sam nasao koje mi je omogucilo prepoznavanje prosirenog Requesta iz types.d.ts fajla.

2024-12-02 16:32 UTC, igor-at-2c requested changes

2024-12-02 16:32 UTC, igor-at-2c commented on src/repositories/userRepository.ts
> +      throw createError(`Error finding record by ID in table "users": ${error}`, error.statusCode);
Sta ako je error undefined? Isto i u ostalim funkcijama u userRepository i baseRepository

2024-12-02 16:32 UTC, igor-at-2c commented on src/repositories/userRepository.ts
> +      return result.rows[0] || null;
Sta ako je result undefined?

2024-12-02 16:32 UTC, igor-at-2c commented on src/services/authService.ts
> +        throw createError('Invalid credentials', 401);
Ovde je bolje da vratis poruku npr: "User not found", kako bi korisniku bilo jasno da nije pogresio sifru nego pokusava da se uloguje sa pogresnim nalogom

2024-12-02 16:32 UTC, igor-at-2c commented on src/services/eventService.ts
> +      const eventWithCreator = { ...event, creator_id: creatorId };
Nedostaju ti provere ovde i u ostatku eventService.ts. Nije dovoljno hvatanje errora nad bazom, ukoliko nesto pukne u vezi biznis logike, to treba biti "uhvaceno" pre nego sto stigne do baze.

2024-12-03 11:24 UTC, igor-at-2c requested changes

2024-12-03 11:24 UTC, igor-at-2c commented on src/middleware/eventValidationMiddleware.ts
> +  const validEventTypes = ['Meeting', 'Workshop', 'Conference', 'Webinar', 'Social Event'];
U slucajevima gde imas nesto hardkodovano, treba da bude izdvojeno kao globalna konstanta. Razlozi:
- Ispunjavnje DRY principa,
- Nece doci do bug-a jer si na jednom mestu napisao drugu vrednost

2024-12-03 12:38 UTC, igor-at-2c approved these changes

2024-12-03 12:39 UTC, merged